name: Publish package to NPM

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Bump version'
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'premajor'
          - 'preminor'
          - 'prepatch'

jobs:
  publish:
    if: github.actor == 'leanderpaul' && github.triggering_actor == 'leanderpaul' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git user config
        run: |
          git config user.name "Shadow Manager"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Bump version
        run: bunx release-it ${{ github.event.inputs.bump }} --ci
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
